spring:
  application:
    name: Notification-Service

  mail:
    host: ${HOST_SERVICE_NAME}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIl_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://mysql-db:3306/notificationdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_PASS}
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${SERVER_PORT:8085}

constant:
  email:
    cc: "xyz@gmail.com"
    sender: ${EMAIL_USERNAME}
    enabled: ${EMAIL_ENABLED:true}

secret:
  header:
    key: ${SECRET_HEADER_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/



