spring:
  application:
    name: Notification-Service

  mail:
    host: ${HOST_SERVICE_NAME}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIl_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/notificationDB
    username: root
    password: ${DB_PASSWORD}
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${SERVER_PORT}

constant:
  email:
    cc: ${CC_EMAIL_ID}
    sender: ${EMAIL_USERNAME}
    enabled: ${EMAIL_ENABLED:true}

secret:
  header:
    key: ${SECRET_HEADER_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



